//! Build script: auto-discovers `assets/*/dance.json` metadata files and
//! generates static frame arrays + a `DANCES` catalogue so the binary
//! embeds all animation frames at compile time.
//!
//! To add a new dance you no longer need to edit this file — just:
//!   1. `mkdir assets/dance3 && cp new.gif assets/dance3/dance.gif`
//!   2. `python3 scripts/convert.py assets/dance3/dance.gif assets/dance3/`
//!   3. `cargo build`  ← dance3 is picked up automatically.

use std::env;
use std::fs;
use std::path::Path;

use serde::Deserialize;

#[derive(Deserialize)]
struct DanceMeta {
    name: String,
    fps_ms: u64,
}

fn main() {
    let out_dir = env::var("OUT_DIR").unwrap();
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").unwrap();
    let assets_dir = Path::new(&manifest_dir).join("assets");

    let mut generated = String::from("/// Auto-generated by build.rs — DO NOT EDIT.\n");
    let mut catalogue_entries: Vec<String> = Vec::new();

    // ── Auto-discover all assets/*/dance.json files ─────────────────
    let mut dance_dirs: Vec<_> = fs::read_dir(&assets_dir)
        .expect("Cannot read assets/")
        .filter_map(|e| e.ok())
        .filter_map(|entry| {
            let path = entry.path();
            let meta_path = path.join("dance.json");
            if meta_path.is_file() {
                Some((path, meta_path))
            } else {
                None
            }
        })
        .collect();

    // Sort so the generated code is deterministic
    dance_dirs.sort_by_key(|(dir, _)| dir.file_name().unwrap_or_default().to_owned());

    assert!(
        !dance_dirs.is_empty(),
        "No assets/*/dance.json found. Run scripts/convert.py first."
    );

    for (dance_dir, meta_path) in &dance_dirs {
        let meta_json = fs::read_to_string(meta_path)
            .unwrap_or_else(|e| panic!("Cannot read {:?}: {}", meta_path, e));
        let meta: DanceMeta = serde_json::from_str(&meta_json)
            .unwrap_or_else(|e| panic!("Bad JSON in {:?}: {}", meta_path, e));

        let dance_name = &meta.name;
        let fps_ms = meta.fps_ms;

        // ── Scan for frame files ──────────────────────────────────
        let mut frame_files: Vec<_> = fs::read_dir(dance_dir)
            .unwrap_or_else(|e| panic!("Cannot read {:?}: {}", dance_dir, e))
            .filter_map(|entry| {
                let entry = entry.ok()?;
                let name = entry.file_name().to_string_lossy().to_string();
                if name.starts_with("frame_") && name.ends_with(".txt") {
                    Some((name, entry.path()))
                } else {
                    None
                }
            })
            .collect();

        frame_files.sort_by(|a, b| a.0.cmp(&b.0));

        assert!(
            !frame_files.is_empty(),
            "No frame_*.txt files found in {:?}",
            dance_dir
        );

        // ── Read and embed each frame ─────────────────────────────
        let const_name = format!("{}_FRAMES", dance_name.to_uppercase());

        let mut array_entries = Vec::with_capacity(frame_files.len());

        for (name, path) in &frame_files {
            let content = fs::read_to_string(path)
                .unwrap_or_else(|e| panic!("Cannot read {:?}: {}", path, e));

            let normalised: String = content
                .lines()
                .map(|l| l.trim_end())
                .collect::<Vec<_>>()
                .join("\n");

            let escaped = escape_rust_string(&normalised);
            array_entries.push(format!("    // {}\n    \"{}\"", name, escaped));
        }

        generated.push_str(&format!(
            "/// {} animation frames ({} frames).\n\
             pub static {}: &[&str] = &[\n{}\n];\n\n",
            dance_name,
            array_entries.len(),
            const_name,
            array_entries.join(",\n"),
        ));

        catalogue_entries.push(format!(
            "    (\"{}\", {}, {})",
            dance_name, const_name, fps_ms
        ));

        // Re-run build script if the dance directory changes
        println!("cargo:rerun-if-changed=assets/{}/", dance_name);
    }

    // ── Write the catalogue ───────────────────────────────────────
    generated.push_str(&format!(
        "/// All available dances: (name, frames, ms_per_frame).\n\
         pub static DANCES: &[(&str, &[&str], u64)] = &[\n{}\n];\n",
        catalogue_entries.join(",\n"),
    ));

    let dest = Path::new(&out_dir).join("frames.rs");
    fs::write(&dest, generated).unwrap_or_else(|e| panic!("Cannot write {:?}: {}", dest, e));
}

/// Escape a string for embedding inside a Rust `"…"` literal.
fn escape_rust_string(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for ch in s.chars() {
        match ch {
            '\\' => out.push_str(r"\\"),
            '"' => out.push_str("\\\""),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            c if c.is_control() => out.push_str(&format!("\\u{:04x}", c as u32)),
            c => out.push(c),
        }
    }
    out
}
